### ISSUE TITLE
Creating a new droplet can take a while

### ISSUE THREAD

**Issue by toin0u** [toin0u/DigitalOcean#15]
https://www.digitalocean.com/community/questions/api-for-event-polling

Maybe we can poll until the `status` changes from `new` to `active`.

**Comment by taylorotwell** [comment]
If you poll, make that an optional feature, so that people can poll in a queue or something if they want.

**Comment by toin0u** [comment]
You're right I think it's the best way to do that. Thanks for your input :)

**Comment by toin0u** [comment]
Maybe the /Event from their API will help to fix this :)
