### ISSUE TITLE
Add /domains

### ISSUE THREAD

**Issue by toin0u** [toin0u/DigitalOcean#23]
https://www.digitalocean.com/api

**Comment by taylorotwell** [comment]
I would definitely appreciate this. Will send you $30 if that helps.

**Comment by toin0u** [comment]
Thanks for your proposition. I don't have a free domain right now so why not ?
Or maybe you have a domain name you do not use ? It will help me to add /domais this for sure :)

**Comment by taylorotwell** [comment]
Don't think you really need an actual domain to make the calls. It will add the records even if the domain doesn't exist.

**Comment by toin0u** [comment]
Actually I did not tested yet.. I will and keep you updated :)

**Comment by toin0u** [comment]
I'm going to write the CLI + tests and update de doc before to release a new version :)

**Comment by taylorotwell** [comment]
Sweet!

**Comment by toin0u** [comment]
1.3.0 released :) https://github.com/toin0u/DigitalOcean/releases/tag/1.3.0

**Comment by taylorotwell** [comment]
What's your PayPal?

**Comment by toin0u** [comment]
paypal@sbin.dk :)
