### ISSUE TITLE
Problems sending requests

### ISSUE THREAD

**Issue by gustavomanolo** [toin0u/DigitalOcean#26]
Hi, i'm having a problem when trying to retrieve the list of regions:
Impossible to process this query: https:\/\/api.digitalocean.com\/regions\/?client_id=CLIENT_ID&api_key=API_KEY i've installed all the libraries/dependencies with composer, and i don't know what else i could do, if something like a php library.

Thank you.

**Comment by toin0u** [comment]
Hi,

First of all, I've edited your issue to remove your credentials. But you **must** change your API creadentials in Digital Ocean **asap** !!!

I've tested it's should be ok..
![screen shot 2013-08-09 at 10 01 12 am](https://f.cloud.github.com/assets/672421/936963/340b9562-00ca-11e3-8f0f-8170a149d7dc.png)

Then can you paste the ouput of `composer show -i` ?

**Comment by gustavomanolo** [comment]
Thanks a lot, i got this from "composer show -i":
knplabs/github-api      dev-master 8a8f304 GitHub API v3 client
kriswallsmith/buzz      dev-master d7545a9 Lightweight HTTP client
sendgrid/sendgrid       1.0.4              This library allows you to quickly and e...
swiftmailer/swiftmailer v5.0.1             Swiftmailer, free feature-rich PHP mailer
symfony/console         dev-master a315258 Symfony Console Component
symfony/yaml            dev-master 4d80b4f Symfony Yaml Component
toin0u/digitalocean     1.2.0              DigitalOcean API PHP 5.3+ library
toin0u/http-adapter     dev-master 0a23934 HttpAdapter PHP 5.3+ library

**Comment by gustavomanolo** [comment]
This only happens when i clone my project in a remote server, (Ubuntu 12.04), if you need any technical info from my server, let me know.
It works perfectly on my local machines.

**Comment by toin0u** [comment]
Which version of php do you use ?
I can see that the url is escaped. Can you paste the `php -i | grep quotes` output ?

**Comment by gustavomanolo** [comment]
Here's the output of php "php -i | grep quotes":
magic_quotes_gpc => Off => Off
magic_quotes_runtime => Off => Off
magic_quotes_sybase => Off => Off

**Comment by gustavomanolo** [comment]
This is the versions of PHP, that i'm using:
PHP 5.3.10-1ubuntu3.7 with Suhosin-Patch (cli) (built: Jul 15 2013 18:05:44) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

**Comment by gustavomanolo** [comment]
Any suggests?

**Comment by toin0u** [comment]
Can you runs tests in your remote server ?

**Comment by gustavomanolo** [comment]
**Got this running "bootstrap.php"**
You need to install the project dependencies using Composer: $ wget http://getcomposer.org/composer.phar OR $ curl -sS https://getcomposer.org/installer | php $ php composer.phar install --dev $ phpunit

**Running DigitalOceanTest.php**
Fatal error: Class 'DigitalOcean\Tests\TestCase' not found in /www/inc/clases/composer/vendor/toin0u/digitalocean/tests/DigitalOcean/Tests/DigitalOceanTest.php on line 20

**Running TestCase.php**
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /www/inc/clases/composer/vendor/toin0u/digitalocean/tests/DigitalOcean/Tests/TestCase.php on line 18

**Comment by toin0u** [comment]
Well, the best way is to clone the repo, install dependencies and run tests.

> http://shelr.tv/records/520aa01396608048d2000065

**Comment by gustavomanolo** [comment]
**Here is the output of PHPUnit**
Configuration read from /www/inc/clases/composer/vendor/toin0u/digitalocean/phpunit.xml.dist

........I......................................................  63 / 207 ( 30%)
............................................................... 126 / 207 ( 60%)
...S........................................................... 189 / 207 ( 91%)
..................

Time: 445 ms, Memory: 30.00Mb

OK, but incomplete or skipped tests!
Tests: 207, Assertions: 1087, Incomplete: 1, Skipped: 1.

**Comment by toin0u** [comment]
Thanks for the repport.

Can you rename `phpunit.xml.dist` to `phpunit.xml` as I described [here](https://github.com/toin0u/DigitalOcean#unit-tests) ? And run the tests again :)

**Comment by gustavomanolo** [comment]
Here is the new output:

PHPUnit 3.7.24 by Sebastian Bergmann.

Configuration read from /home/DigitalOcean/phpunit.xml

........I......................................................  63 / 207 ( 30%)
............................................................... 126 / 207 ( 60%)
...S........................................................... 189 / 207 ( 91%)
..................

Time: 10.56 seconds, Memory: 34.50Mb

OK, but incomplete or skipped tests!
Tests: 207, Assertions: 1087, Incomplete: 1, Skipped: 1.

Code Coverage Report 
  2013-08-14 13:49:39

 Summary: 
  Classes: 97.67% (42/43)
  Methods: 99.12% (113/114)
  Lines:   93.75% (705/752)

\DigitalOcean::AbstractDigitalOcean
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% ( 16/ 16)
\DigitalOcean::Credentials
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% (  5/  5)
\DigitalOcean::DigitalOcean
  Methods: 100.00% ( 6/ 6)   Lines: 100.00% (  8/  8)
\DigitalOcean\CLI::Command
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% (  4/  4)
\DigitalOcean\CLI\Droplets::CreateCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Droplets::CreateInteractiveCommand
  Methods: 100.00% ( 6/ 6)   Lines:  45.98% ( 40/ 87)
\DigitalOcean\CLI\Droplets::DestroyCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\Droplets::DisableAutomaticBackupsCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\Droplets::EnableAutomaticBackupsCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\Droplets::PowerCycleCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\Droplets::PowerOffCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\Droplets::PowerOnCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\Droplets::RebootCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\Droplets::RebuildCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Droplets::RenameCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Droplets::ResetRootPasswordCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 21/ 21)
\DigitalOcean\CLI\Droplets::ResizeCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Droplets::RestoreCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Droplets::ShowAllActiveCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 17/ 17)
\DigitalOcean\CLI\Droplets::ShowCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\Droplets::ShutdownCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\Droplets::SnapshotCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\Images::DestroyCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 18/ 18)
\DigitalOcean\CLI\Images::GetAllCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 17/ 17)
\DigitalOcean\CLI\Images::GetGlobalCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 17/ 17)
\DigitalOcean\CLI\Images::GetMyImagesCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 17/ 17)
\DigitalOcean\CLI\Images::ShowCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 15/ 15)
\DigitalOcean\CLI\Images::TransfertCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 24/ 24)
\DigitalOcean\CLI\Regions::GetAllCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\SSHKeys::AddCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 20/ 20)
\DigitalOcean\CLI\SSHKeys::DestroyCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 18/ 18)
\DigitalOcean\CLI\SSHKeys::EditCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 26/ 26)
\DigitalOcean\CLI\SSHKeys::GetAllCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\CLI\SSHKeys::ShowCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 15/ 15)
\DigitalOcean\CLI\Sizes::GetAllCommand
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\Droplets::Droplets
  Methods: 100.00% (18/18)   Lines: 100.00% ( 38/ 38)
\DigitalOcean\Images::Images
  Methods: 100.00% ( 7/ 7)   Lines: 100.00% ( 15/ 15)
\DigitalOcean\Regions::Regions
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  4/  4)
\DigitalOcean\SSHKeys::SSHKeys
  Methods: 100.00% ( 6/ 6)   Lines: 100.00% ( 14/ 14)
\DigitalOcean\Sizes::Sizes
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  4/  4)

**Comment by toin0u** [comment]
Thanks but I meant to fill up the phpunit.xml with the your credentials and run the test suite :)
This will retreive your droplets from your account (nothing else). It will be usefull in your case because it will make a real API call to Digital Ocean from your server. The test suite shows that your PHP configuration seems correct.. It's a weird error you have. Can you maybe make a little gist with a sample of your code if possible ?

```
<php>
    <!-- <server name="CLIENT_ID" value="YOUR_CLIENT_ID" /> -->
    <!-- <server name="API_KEY" value="YOUR_API_KEY" /> -->
</php>
```

**Comment by gustavomanolo** [comment]
I've already set my Client_id and Api_key on phpunit.xml. Here's the part of the code where i'm having problems:
https://gist.github.com/gustavomanolo/7a37f1a5d7299560f67b

Normally i call the "get-details.php" and it gaves me an array with result=>1 and all the regions, it works perfectly on my localhost, but when i upload it to my remote server it gives me:
{"result":0,"msg":"Impossible to process this query: https:\/\/api.digitalocean.com\/regions\/?client_id=CLIENT_ID&api_key=API_KEY","regions":[]}

**Comment by toin0u** [comment]
Thanks for the gist. It works for me as well. It's definetly a server misconfiguration I guess..
Did you tried other adapter ie. cURL, Socket or Guzzle ?

**Comment by gustavomanolo** [comment]
Where can i set this options? Like changing between cURL, Socket, Guzzle...

**Comment by toin0u** [comment]
You can see the adapters here: https://github.com/toin0u/HttpAdapter

If you want to use the socket adapter for example:

``` php
$digitalOcean = new DigitalOcean($credentials, new HttpAdapter\SocketHttpAdapter());
```

**Comment by toin0u** [comment]
@gustavomanolo any news ?

**Comment by gustavomanolo** [comment]
HI, now it works perfectly, i had to change to use HttpAdapter\CurlHttpAdapter() insted of the default adapter.

**Comment by toin0u** [comment]
Glad to head that :) I'll so close this issue ;)
Do not hesitate do ask if you face any problem.
