### ISSUE TITLE
Undefined property "message" on error.

### ISSUE THREAD

**Issue by taylorotwell** [toin0u/DigitalOcean#27]
Anytime I get an error from the API I get the following error from the library:

Undefined property: stdClass::$message

/var/www/vendor/toin0u/digitalocean/src/DigitalOcean/AbstractDigitalOcean.php - Line 113

**Comment by toin0u** [comment]
It's true I got the same error sometimes. I think it's because Digital Ocean changed the way they report their errors.

I think the best way to fix this is to revert this [commit](https://github.com/toin0u/DigitalOcean/commit/a87e1653e3cf8b8a1d4d1e60b25b25482035bb54) to handle both cases..
