### ISSUE TITLE
disable pagination

### ISSUE THREAD

**Issue by mourlamstudios** [toin0u/DigitalOcean#38]
with v2 api pagination is enabled by default returning only the first 20 objects
ie. images->getAll() will only return the first 20 of my 57 images i have available. 

you can either follow response links or let us set per_page parameter so we can fetch all objects

links example from v2 api documentation
{
    . . .
    "links": {
        "pages": {
            "last": "https://api.digitalocean.com/v2/images?page=2",
            "next": "https://api.digitalocean.com/v2/images?page=3"
        }
    }
    . . .
}

**Comment by toin0u** [comment]
This library wrapes the version 1 of the DigitalOcean's API: https://developers.digitalocean.com/v1/images/

I think you need to give a look to the v2 :) https://github.com/toin0u/DigitalOceanV2#image

Hope that helps otherwise feel free to reopen this issue :)
