### ISSUE TITLE
Bumping release number?

### ISSUE THREAD

**Issue by ywarnier** [toin0u/DigitalOcean#44]
Hi there,

Your latest release dates from 14/01/2014. However, your latest commits dates from december 2014.
Would you be so kind as to release a new stable version with the latest code? This would reduce the load on our composer process in https://github.com/chamilo/chamilo-lms, where we use it (very occasionally, but it's still in our composer.json) to spawn D.O. instances for the videoconference server (BBB).

Thanks!

**Comment by GrahamCampbell** [comment]
This package should probably be marked as deprecated. It is not for the current version of the digital ocean API.

**Comment by ywarnier** [comment]
OK. Maybe a mention in the readme, then?

**Comment by GrahamCampbell** [comment]
It is mentioned? The very first line in the readme.

**Comment by ywarnier** [comment]
Hem... sorry about that (I'm following various projects about the same thing and missed the first line here). Thanks and Merry Christmas!
